// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHMSXth-Qbids1NtWXZCZH3zYDgei452E',
    appId: '1:922997170231:web:cdc024395691e035b79fb2',
    messagingSenderId: '922997170231',
    projectId: 'skrining-apps',
    authDomain: 'skrining-apps.firebaseapp.com',
    storageBucket: 'skrining-apps.firebasestorage.app',
    measurementId: 'G-70KE6LN219',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjaYoFlJaxJPdhzkp0Iq1fOnTizl471R0',
    appId: '1:922997170231:android:02feee789c595cd4b79fb2',
    messagingSenderId: '922997170231',
    projectId: 'skrining-apps',
    storageBucket: 'skrining-apps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDPqWfsANY2qRhbl7G24ghzKayWqYzt3Q',
    appId: '1:922997170231:ios:9f6c0164acc836acb79fb2',
    messagingSenderId: '922997170231',
    projectId: 'skrining-apps',
    storageBucket: 'skrining-apps.firebasestorage.app',
    iosBundleId: 'com.example.skriningApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDPqWfsANY2qRhbl7G24ghzKayWqYzt3Q',
    appId: '1:922997170231:ios:9f6c0164acc836acb79fb2',
    messagingSenderId: '922997170231',
    projectId: 'skrining-apps',
    storageBucket: 'skrining-apps.firebasestorage.app',
    iosBundleId: 'com.example.skriningApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHMSXth-Qbids1NtWXZCZH3zYDgei452E',
    appId: '1:922997170231:web:c29b88181841e189b79fb2',
    messagingSenderId: '922997170231',
    projectId: 'skrining-apps',
    authDomain: 'skrining-apps.firebaseapp.com',
    storageBucket: 'skrining-apps.firebasestorage.app',
    measurementId: 'G-M16YEXC67H',
  );
}
